spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://database:5432/schedule_boot
    username: postgres
    password: root
    initialization-mode: always
    sql-script-encoding: UTF-8
    driver-class-name: org.postgresql.Driver
  devtools:
    remote:
      secret: scheduleapp
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  thymeleaf: 
    cache: false
    encoding: UTF-8
  messages:
    encoding: UTF-8
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    org:
      hibernate:
        SQL: debug
app:
  title: 'DVFU SCHEDULE'